// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Formplug","status":true,"description":"Allows users to give a thumbs up, down or Wiggle to Formbar and interact with Formbar API via socket.io-client.","parameters":{"Formbar URL":"https://formbeta.yorktechapps.com/","API Key":"6f02253537d49075d120fa68c35f9a84fe8217c1cd57be29053cef4e30feccb7a443ff56f941e8c6ecc6c1463ee792279bf7b14beb4b0738e5c1d1765afa97ba"}}
];
